trigger:
  paths:
    include:
      - backend/*

pool: self-hosted

variables:
- group: backend

- name: imageName
  value: backend
- name: imageTag
  value: $(Build.BuildId)
- name: awsAccountId
  value: '235110230377'
- name: awsRegion
  value: 'us-east-1'
- name: repositoryName
  value: 'ecommerce/backend'
- name: clusterName
  value: 'ecommerce-dev-cluster'
- name: serviceName
  value: 'my-backend-service'

stages:

# =========================
# BUILD & PUSH
# =========================
- stage: BuildAndPush
  jobs:
  - job: Docker_Process
    steps:

    - script: docker system prune -af
      displayName: Clean Docker

    - script: |
        cd backend
        docker build -t $(imageName):$(imageTag) .
      displayName: Build Docker Image

    - task: ECRPushImage@1
      displayName: Push to ECR
      inputs:
        awsCredentials: 'aws-service-connection'
        regionName: '$(awsRegion)'
        imageSource: 'imageName'
        sourceImageName: '$(imageName)'
        sourceImageTag: '$(imageTag)'
        sourceImageId: '$(imageName):$(imageTag)'
        repositoryName: '$(repositoryName)'
        pushTag: latest

# =========================
# DEPLOY
# =========================
- stage: DeployToECS
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    steps:

    # 🔧 Prepare task definition JSON
    - powershell: |
        $image = "$(awsAccountId).dkr.ecr.$(awsRegion).amazonaws.com/$(repositoryName):$(imageTag)"

        (Get-Content backend/taskdef.json) `
          -replace "REPLACE_IMAGE", $image `
          -replace "REPLACE_DB", "$(DATABASE_URL)" `
          -replace "REPLACE_SECRET", "$(SECRET_KEY)" |
          Set-Content new-taskdef.json
      displayName: "Prepare Task Definition"

    # 🚀 Register new revision
    - task: AWSCLI@1
      displayName: Register Task Definition
      inputs:
        awsCredentials: 'aws-service-connection'
        regionName: '$(awsRegion)'
        awsCommand: 'ecs'
        awsSubCommand: 'register-task-definition'
        awsArguments: '--cli-input-json file://new-taskdef.json'

    # 🔥 Deploy latest revision
    - task: AWSCLI@1
      displayName: Update ECS Service
      inputs:
        awsCredentials: 'aws-service-connection'
        regionName: '$(awsRegion)'
        awsCommand: 'ecs'
        awsSubCommand: 'update-service'
        awsArguments: '--cluster $(clusterName) --service $(serviceName) --force-new-deployment'