trigger:
  paths:
    include:
      - frontend/*

pool: self-hosted

variables:
  - group: terraform-secrets
  - name: Name
    value: frontend
  - name: imageTag
    value: $(Build.BuildId)

  # Replace with your actual ECR Repository Name
  
  

stages:
  - stage: BuildAndPush
    displayName: "Build and Push Frontend"
    jobs:
      - job: Docker_Process
        displayName: "Docker Build and ECR Push"
        steps:
          # 1. Build the image locally on the agent
          - script: |
              cd frontend
              docker build -t $(Name):$(imageTag) --build-arg VITE_API_BASE_URL=$(VITE_API_BASE_URL_SECRET) .
            displayName: "Build Docker Image"

          # 2. Push to ECR using the AWS Task
          # This task handles the 'docker login' and 'docker push' logic for you

          # Alternative if the first one fails
          - task: SecretsManagerGetSecret@1
            inputs:
              awsCredentials: 'aws-service-connection'
              regionName: 'us-east-1'
              secretIdOrName: 'ecommerce-dev-metadata'
              variableName: 'infra_raw_secret' # Add this line

          - script: |
              echo "$(db_instance_id)";
            

          - task: ECRPushImage@1
            displayName: "Push to Amazon ECR"
            inputs:
              awsCredentials: 'aws-service-connection'
              regionName: 'us-east-1'
              imageSource: 'imageName'
              sourceImageName: '$(Name)'
              sourceImageId: '$(Name):$(imageTag)'
              sourceImageTag: '$(imageTag)'
              repositoryName: 'ecommerce/frontend'
              pushTag: '$(imageTag)'

          
  - stage: DeployToECS
    displayName: "Deploy to Amazon ECS"
    dependsOn: BuildAndPush
    condition: succeeded()
    jobs:
      - job: Update_ECS_Service
        displayName: "Update ECS Service"
        steps:
          - powershell: |
              if (!(Get-Command aws -ErrorAction SilentlyContinue)) {
                  Write-Host "AWS CLI not found, installing..."
                  $msiPath = "$($env:TEMP)\AWSCLIV2.msi"
                  Invoke-WebRequest "https://awscli.amazonaws.com/AWSCLIV2.msi" -OutFile $msiPath
                  Start-Process msiexec.exe -ArgumentList "/i $msiPath /quiet /qn /norestart" -Wait
              } else {
                  Write-Host "AWS CLI is already installed."
              }
            displayName: 'Install AWS CLI'

          - powershell: |
              (Get-Content frontend/task-definition.json) `
                -replace 'IMAGE_TAG', '$(Build.BuildId)' `
                | Set-Content frontend/task-definition-rendered.json

            displayName: "Render ECS Task Definition"

          - task: AWSCLI@1
            displayName: "Register ECS Task Definition"

            inputs:
              awsCredentials: 'aws-service-connection'
              regionName: 'us-east-1'

              awsCommand: 'ecs'
              awsSubCommand: 'register-task-definition'

              awsArguments: '--cli-input-json file://frontend/task-definition-rendered.json'
                  
          # This task updates the service to pull the new image tag
          - task: AWSCLI@1
            displayName: "Update ECS Service"
            inputs:
              awsCredentials: 'aws-service-connection' # Your exact Service Connection name
              regionName: 'us-east-1'
              awsCommand: 'ecs'
              awsSubCommand: 'update-service'
              # Use a single line for arguments to prevent Windows parsing errors
              awsArguments: '--cluster ecommerce-dev-cluster --service my-app-service --task-definition my-app-task'