# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - terraform/* 

pool: self-hosted

variables:
  - group: terraform-secrets
  - group: backend
  - name: working_dir
    value: '$(System.DefaultWorkingDirectory)/terraform/env/dev'

stages:  
  - stage: Terraform_Infrastructure
    displayName: 'Deploy AWS Resources'
    jobs:
      - job: Terraform_Apply
        displayName: 'Terraform Init, Plan & Apply'
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        # 1. Initialize with S3 Backend
        - task: TerraformTaskV4@4
          displayName: 'Terraform Init'
          inputs:
            provider: 'aws'
            command: 'init'
            workingDirectory: '$(working_dir)'
            backendServiceAWS: 'aws-terraform-connection'
            backendAWSBucketName: 'ecommerce-dev-bucket-123456789'
            backendAWSKey: 'ecommerce/terraform.tfstate'
            

        # 2. Generate Plan
        - task: TerraformTaskV4@4
          displayName: 'Terraform Plan'
          inputs:
            provider: 'aws'
            command: 'plan'
            workingDirectory: '$(working_dir)'
            environmentServiceNameAWS: 'aws-terraform-connection'
            commandOptions: >
              -var="database_url=$(DATABASE_URL)"
              -var="secret_key=$(SECRET_KEY)"
              -var="db_password=$(DB_PASSWORD)"


        # 3. Apply Changes
        - task: TerraformTaskV4@4
          displayName: 'Terraform Apply'
          inputs:
            provider: 'aws'
            command: 'apply'
            workingDirectory: '$(working_dir)'
            environmentServiceNameAWS: 'aws-terraform-connection'
            commandOptions: >
              -auto-approve
              -var="database_url=$(DATABASE_URL)"
              -var="secret_key=$(SECRET_KEY)"
              -var="db_password=$(DB_PASSWORD)"

        # # 4. Destroy Plan
        # - task: TerraformTaskV4@4
        #   displayName: 'Terraform Destroy'
        #   inputs:
        #     provider: 'aws'
        #     command: 'destroy'
        #     workingDirectory: '$(working_dir)'
        #     environmentServiceNameAWS: 'aws-terraform-connection'
        #     commandOptions: >
        #       -auto-approve
        #       -var="database_url=$(DATABASE_URL)"
        #       -var="secret_key=$(SECRET_KEY)"
        #       -var="db_password=$(DB_PASSWORD)"
